### PR TITLE
My contribution

### PR DESCRIPTION
**Pull request by elsa-linu**
# Fix to  Issue # 
===============================

===============================
## Checklist

- [yes ] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [ yes] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [ yes] My project uses dependencies
- [yes ] I starred the repo
- [ definetly] I had fun contributing!

### CODE REVIEW

**Comment by elsa-linu** [comment]
Hi @theadeyemiolayinka, please review and accept my PR. Thank you!

**Review by theadeyemiolayinka — CHANGES_REQUESTED** [review]
Could you please remove the windows OS generated .DS_Store files and add the README, requirements to the TicTacToe folder to make your submission compliant to the contributing guidelines?
Thank you.

**Comment by theadeyemiolayinka** [comment]
Project reviewed and merged.
Thank you @elsa-linu
Feel free to add more projects.

**Comment by elsa-linu** [comment]
Sure, Thanks a lot @theadeyemiolayinka :)

**Pull request merged**
