### PR TITLE
Create PythonSnakeGame.py

### PR DESCRIPTION
**Pull request by riya02002**
snake game by using python

# Fix to  Issue # 
===============================

===============================
## Checklist

- [x] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [x] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [x] My project uses dependencies
- [x] I starred the repo
- [x] I had fun contributing!

### CODE REVIEW

**Comment by riya02002** [comment]
python project for hacktoberfest

**Review by theadeyemiolayinka — CHANGES_REQUESTED** [review]
Please follow the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md) and send a new PR.
Cheers!

**Comment by theadeyemiolayinka** [comment]
@riya02002 
Howdy?, you haven't responded to the review.

**Comment by theadeyemiolayinka** [comment]
@riya02002

**Pull request closed without merging**
